name: Publish Docker Image

on:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: cnet_ea_builder

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    -
      name: Git checkout
      uses: actions/checkout@v4
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build Docker Image
      run: docker build . --file Dockerfile --tag "$IMAGE_NAME"
    -
      name: Push Docker Image to GitHub Container Registry
      run: |
        IMAGE_ID="ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}"
        docker tag "${IMAGE_NAME}:latest" "${IMAGE_ID}:latest"
        docker push "${IMAGE_ID}:latest"
